# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Recursos de Google para CoBach BC"
email: admin@cobachbc.edu.mx
description: "Todo lo que necesitas saber sobre tu cuenta @cobachbc.edu.mx"
baseurl: ""
url: "http://google.cobachbc.edu.mx/"
twitter_username: 
github_username:  
color_theme:  "#555555"
color_text:  "#fff"
language:  "es"

# Build settings
markdown: kramdown
permalink: /:title/
gems: [jekyll-paginate]
paginate: 5

# Plugins
plugins_dir:
  - jekyll-admin
